name: Publish Docker

on:
  push:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scrybe_frontend

    steps:
    - name: Publish to Registry
      uses: actions/checkout@v3


    - uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: myDocker/repository
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        tags: "latest,another"

    - name: push
      run: |
        docker build -t vicdam/scrybefrontend .
        docker push vicdam/scrybefrontend