name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./scrybe_frontend

    steps:
    - uses: actions/checkout@v3
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v4

      with:
        name: myDocker/repository
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        tags: "latest,another"
      
      run: |
          docker build -t vicdam/scrybefrontend .
          docker push vicdam/scrybefrontend